version: '3'

services:
  php:
    image: php:7.4-cli
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app/
    # command: php ./SkGovernmentParser/dev.php
    command: tail -f /dev/null
