name: Library Unit Tests

on: [push, pull_request]

jobs:
  tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP with composer v2 and php unit
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2, phpunit:9

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Test with phpunit
        run: vendor/bin/phpunit --coverage-text --testdox tests
